[package]
name = "rustybricks"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.3"
rand = "0.8.5"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies
[profile.dev.package."*"]
opt-level = 3
